routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/neworg', function () {return view('auth.registeror');})->name('neworg');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/meeting', 'MeetingController@index')->name('meetings');
Route::get('/users', 'UserController@index')->name('users');
Route::get('/users', 'UserController@index')->name('userPage');

// routh for task
Route::resource('/task', 'TaskController')->middleware('auth');;
Route::get('task', 'TaskController@index')->name('task');
Route::get('task/delete/{id}', 'TaskController@destroy')->name('delete');
Route::get('task/doneTask/{id}', 'TaskController@doneTask')->name('doneTask');
// end routh for task

// routh for topic
Route::resource('/topic', 'TopicController')->middleware('auth');;
Route::get('topic/delete/{id}', 'TopicController@destroy')->name('delete');
Route::get('topic/done/{id}', 'TopicController@done')->name('done');
// end routh for topic

Route::resource('meetings', 'MeetingController')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);



	Route::resource('mail', 'MailController')->middleware('auth');
	Route::post('send/email', 'MailController@sendemail');



});

app/Meeting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;
class Meeting extends Model
{

    protected $fillable = [
        'title', 'date', 'hour',

    ];
    public function user()
    {
        return $this->belongsToMany('App\User');
    }
    

}

app/Http/Controllers/MeetingController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use App\Meeting;
use App\Topic;
use App\Organization;
use App\Participant;
use App\User;
use App\Task;
class MeetingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id= Auth::id();
        $user = User::find($id);
        $participant = $user-> participants;
        $meeting = Meeting::all();
        $orgs= Organization::find($id);
        return view('meetings.index',['users' => User::all(),'meetings'=>$meeting,'orgs' => Organization::where('user_id', $id)->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {   
            if (Auth::check())
            {
                if (Gate::denies('admin')) {
                    if (Gate::denies('meetingorganizer')) {
                        abort(403,"Permission Denied");
                   }
            }
            return view ('meetings.create', ['organization'=>Auth::user()->organization, 'users'=>User::all()]);
            }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::check())
            {
                if (Gate::denies('admin')) 
                {
                    if (Gate::denies('meetingorganizer')) 
                    {
                        abort(403,"Permission Denied");
                    }
                }
            }
        $meeting = new Meeting();
        $id = Auth::id();
        $meeting->title = $request->name;
        $meeting->user_id = $id;
        $meeting->date = $request->date;
        $meeting->hour = $request->hour;
        $meeting->participants=$request->participants;
        $meeting->save();
        
        $mid = $meeting->id;
        $topic_title = $request->input('topic_title');
        $topic_hour = $request->input('topic_hour');
        for ($i=0; $i <count($topic_title) ; $i++) { 
            $topic = new Topic();
            $topic->topic_title = $topic_title[$i];
            $topic->topic_hour = $topic_hour[$i];
            $topic->meeting_id = $mid;
            $topic->save();
        }
        

        
        $participant = new Participant();
        $participant->user_id = $request->participants;
        $participant->meeting_id = $mid;
        $participant->save();
        
        return redirect('meetings');

        
       
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::check())
        {
            if (Gate::denies('admin')) 
            {
                if (Gate::denies('meetingorganizer')) 
                {
                    abort(403,"Permission Denied");
                }
            }
        }
        $orgs= Organization::find($id);
        $meeting = Meeting::find($id);
        return view('meetings.edit',['meeting'=>$meeting,'orgs' => Organization::where('user_id', $id)->get()]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::check())
            {
                if (Gate::denies('admin')) 
                {
                    if (Gate::denies('meetingorganizer')) 
                    {
                        abort(403,"Permission Denied");
                    }
                }
            }
        $meeting = Meeting::find($id);
        $meeting ->update($request->all());    
        return redirect('meetings');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::check())
        {
            if (Gate::denies('admin')) 
            {
                if (Gate::denies('meetingorganizer')) 
                {
                    abort(403,"Permission Denied");
                }
            }
        }
        $meeting = Meeting::find($id);
            $meeting ->delete();
        
        $meeting_id = $id;
        $topic = Topic::where('meeting_id',$id);
            $topic ->delete();
        $participant = Participant::where('meeting_id',$id);
            $participant ->delete(); 
        
        return redirect('meetings');
    }
}

resources/views/meetings/create.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Create a new meeting') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('meetings.create') }}" class="btn btn-sm btn-primary">{{ __('Add Meeting') }}</a>
                            </div>
                        </div>
                    </div>
                    <div id="box">
                    <form method="post" action="{{ action('MeetingController@store') }}" autocomplete="on">
                            @csrf
                            

                            <div class="pl-lg-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="name">{{ __('Name of the meeting') }}</label>
                                    <input type="text" name="name"  class="form-control form-control-alternative" placeholder="{{ __('Name of the meeting') }}" value="" required>
                                </div>
                        
                                <div class="form-group">
                                    <label class="form-control-label" for="date">{{ __('Date of the meeting') }}</label>
                                    <input type="date" name="date"  class="form-control form-control-alternative" placeholder="{{ __('Date  of the meeting') }}" value="" required>
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="hour">{{ __('Hour of the meeting') }}</label>
                                    <input type="time" name="hour"  class="form-control form-control-alternative" placeholder="{{ __('Hour of the meeting') }}" value="" required>
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="participants" >{{ __('Participants') }}</label>
                                    <input><select class="js-example-basic-multiple" name="participants" multiple="multiple">
                                        <option value="{{Auth::user()->id}}" selected>Myself</option>
                                        @foreach($users as $user)
                                            @if($user->org_id==Auth::user()->org_id && $user->id != Auth::user()->id )          
                                            <option value="{{ $user->id }}">{{ $user->name }}</option>        
                                            @endif
                                        @endforeach
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="topic_title">{{ __('Topics') }}</label>
                                    <input type="text" name="topic_title[]"  class="form-control form-control-alternative" placeholder="{{ __('Topics of the meeting') }}" value="" required><br>
                                    <input type="time" name="topic_hour[]"  class="form-control form-control-alternative"  value="" required>

                                </div>
                                

                                <div id='topics'>

                                </div>
                                <div  id ="add">
                                <a class="btn btn-info mt-2" >{{ __('Add topic') }}</a>
                                 </div>
                                 

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4" value="Save">{{ __('Create') }}</button>
                                </div>
                            </div>
                        </form>
                      </div>
                    
                    
                    
                </div>
            </div>
        </div>

        <script>

                function createTicketComponent(type) {
                type = type || null;
                
                var elements   = [],
                    rootElement = document.createElement('tr');
                        
                elements.push('<label class="form-control-label" for="topic">{{ __('Topics') }}</label><input type="text" name="topic_title[]"  class="form-control form-control-alternative" placeholder="{{ __('Topics of the meeting') }}" value="" required><br>');
                elements.push('<input type="time" name="topic_hour[]"  class="form-control form-control-alternative"  value="" required><br>');
                
                    
                rootElement.innerHTML = elements.join('');
                
                return rootElement;
                }


              


                function onClickCreateTicketButton(event) {
                var button    = event.target,
                    container = document.querySelector('#topics'),
                    component;

                
                    component = createTicketComponent();
                

                container.appendChild(component);
                }

                
                var buttonsGroup = document.getElementById('add');
                buttonsGroup.addEventListener('click', onClickCreateTicketButton);



</script>
            
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/meetings/edit.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Edit your meeting') }}</h3>
                            </div>
                        </div>
                    </div>
                    <form method="post" action="{{ action('MeetingController@update',$meeting->id) }}" autocomplete="on">
                            @csrf
                            @method('PATCH')

                            <div class="pl-lg-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="title">{{ __('Name of the meeting') }}</label>
                                    <input type="text" name="title"  class="form-control form-control-alternative" placeholder="{{ __('Name of the meeting') }}" value="{{$meeting->title}}" >
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="date">{{ __('Date of the meeting') }}</label>
                                    <input type="date" name="date"  class="form-control form-control-alternative" placeholder="{{ __('Date  of the meeting') }}" value="{{$meeting->date}}" >
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="hour">{{ __('Hour of the meeting') }}</label>
                                    <input type="time" name="hour"  class="form-control form-control-alternative" placeholder="{{ __('Hour of the meeting') }}" value="{{$meeting->hour}}" >
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4" value="Update">{{ __('Update') }}</button>
                                </div>
                            </div>
                        </form>
                  

                    
                    
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/meetings/index.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Meetings') }}</h3>
                            </div>
                            @cannot('employee')<div class="col-4 text-right">
                                <a href="{{ route('meetings.create') }}" class="btn btn-sm btn-primary">{{ __('Add Meeting') }}</a>
                            </div> @endcannot
                        </div>
                    </div>
                    
                  

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Name') }}</th>
                                    <th scope="col">{{ __('Creator') }}</th>
                                    <th scope="col">{{ __('Date') }}</th>
                                    <th scope="col">{{ __('Hour') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($meetings as $meeting)
                                    <tr>
                                        <td>
                                        <a href="{{ route('task') }}">{{ $meeting->title }}</a>
                                        </td>
                                        <td>{{ $meeting->user_id }}</td>
                                        <td>{{ $meeting->date }}</td>
                                        <td>{{ $meeting->hour }}</td>
                                       @cannot('employee')
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                   
                                                        <form action="{{ route('meetings.destroy', $meeting) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            
                                                            <a class="dropdown-item" href="{{ route('meetings.edit', $meeting) }}">{{ __('Edit') }}</a>
                                                            <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this meeting?") }}') ? this.parentElement.submit() : ''">
                                                                {{ __('Delete') }}
                                                            </button>
                                                        </form>    
                                                    
                                                       
                                                </div>
                                            </div>
                                        </td>
                                        @endcannot
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection