routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/neworg', function () {return view('auth.registeror');})->name('neworg');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/meeting', 'MeetingController@index')->name('meetings');
Route::get('/users', 'UserController@index')->name('users');
Route::get('/users', 'UserController@index')->name('userPage');

// routh for task
Route::resource('/task', 'TaskController')->middleware('auth');;
Route::get('task', 'TaskController@index')->name('task');
Route::get('task/delete/{id}', 'TaskController@destroy')->name('delete');
Route::get('task/doneTask/{id}', 'TaskController@doneTask')->name('doneTask');
// end routh for task

// routh for topic
Route::resource('/topic', 'TopicController')->middleware('auth');;
Route::get('topic/delete/{id}', 'TopicController@destroy')->name('delete');
Route::get('topic/done/{id}', 'TopicController@done')->name('done');
// end routh for topic

Route::resource('meetings', 'MeetingController')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);



	Route::resource('mail', 'MailController')->middleware('auth');
	Route::post('send/email', 'MailController@sendemail');



});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Meeting;
use App\User;
use App\Organization;
class Task extends Model
{
      protected $fillable = [
        'title', 'due_date','name','status'
    
    ];
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Collection;
use App\Topic;
use App\Organization;
use App\User;
use App\Task;
use App\Meeting;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id= Auth::id();
        $meetingid = DB::table('meetings')->where('id',$id)->first();
        $met = $meetingid->id;
        $task = Meeting::find($id);
        $user = User::find($id);
        $tasks = Task::find($id);
        $topics = Topic::find($id);
        $orgs= Organization::find($id);
        return view('task.index',['users' => User::all(),'tasks'=> Task::all(),'topics'=> Topic::all(),'orgs' => Organization::where('user_id', $id)->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::check())
            {
                if (Gate::denies('admin')) 
                {
                    if (Gate::denies('meetingorganizer')) 
                    {
                        abort(403,"Permission Denied");
                    }
                }
            }
        $id= Auth::id();
        $orgs= Organization::find($id);
        return view('task.create',['orgs' => Organization::where('user_id', $id)->get()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::check())
            {
                if (Gate::denies('admin')) 
                {
                    if (Gate::denies('meetingorganizer')) 
                    {
                        abort(403,"Permission Denied");
                    }
                }
            }
        $task = new Task();
        $id = Auth::id(); //the idea of the current user
        $task->title = $request->title;
        $task->status = 0;
        $task->name = $request->name;
        $task->user_id = $id;
        $task->due_date = $request->due_date;
        $task->meeting_id = $id;
        $task->save();
        return redirect('task');         
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Auth::check())
            {
                if (Gate::denies('admin')) 
                {
                    if (Gate::denies('meetingorganizer')) 
                    {
                        abort(403,"Permission Denied");
                    }
                }
            }
        $orgs= Organization::find($id);
        $task = Task::findOrFail($id);
        return view('task.edit',['task'=>$task,'orgs' => Organization::where('user_id', $id)->get()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Auth::check())
            {
                if (Gate::denies('admin')) 
                {
                    if (Gate::denies('meetingorganizer')) 
                    {
                        abort(403,"Permission Denied");
                    }
                }
            }
        $task = Task::findOrFail($id);            
        $task->update($request->except(['_token'])); 
        return redirect('task');    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Auth::check())
            {
                if (Gate::denies('admin')) 
                {
                    if (Gate::denies('meetingorganizer')) 
                    {
                        abort(403,"Permission Denied");
                    }
                }
            }
        if (Gate::denies('admin')) {
            abort(403,"Sorry you are not allowed to create tasks!");
        }
 
        $task = Task::find($id);
        $task->delete();
        return redirect('task');
    }
    public function doneTask($id)
    {
        if (Auth::check())
            {
                if (Gate::denies('admin')) 
                {
                    if (Gate::denies('meetingorganizer')) 
                    {
                        abort(403,"Permission Denied");
                    }
                }
            }          
        $task = Task::findOrFail($id);            
        $task->status = 1; 
        $task->save();
        return redirect('task');    
    }    
}

resources/views/task/create.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-10">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Create a new task') }}</h3>
                            </div>
                            
                        </div>
                    </div>
                    <div id="box">
                    <form method="post" action="{{ action('TaskController@store') }}" autocomplete="on">
                            @csrf
                            
                            <div class="pl-lg-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="title">{{ __('Name of the task') }}</label>
                                    <input type="text" id="title" name="title"  class="form-control form-control-alternative" placeholder="{{ __('Name of the task') }}" value="" required>
                                </div>
                        <div class="pl-lg-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="name">{{ __('Name of the User') }}</label>
                                    <input type="text" id="name" name="name"  class="form-control form-control-alternative" placeholder="{{ __('Name of the task') }}" value="{{ auth()->user()->name }}" required>
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label" for="due_date">{{ __('Date of the task') }}</label>
                                    <input type="date" id="due_date" name="due_date"  class="form-control form-control-alternative" placeholder="{{ __('Date  of the task') }}" value="" required>
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4" value="Save">{{ __('Create') }}</button>
                                </div>
                            </div>
                        </form>
                      </div>
                    
                    
                    
                </div>
            </div>
        </div>

    
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/task/edit.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Edit your task') }}</h3>
                            </div>
                        </div>
                    </div>
                    <form method="post" action="{{ action('TaskController@update',$task->id) }}" autocomplete="on">
                            @csrf
                            @method('PATCH')

                            <div class="pl-lg-4">
                                <div class="form-group">
                                    <label class="form-control-label" for="title">{{ __('Task Name') }}</label>
                                    <input type="text" name="title"  class="form-control form-control-alternative" placeholder="{{ __('Name of the task') }}" value="{{$task->title}}" >
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="due_date">{{ __('Task Due Date') }}</label>
                                    <input type="date" name="due_date"  class="form-control form-control-alternative" placeholder="{{ __('Due date of the task') }}" value="{{$task->due_date}}" >
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="topic_hour">{{ __('Status') }}</label>
                                    <select name="status"  class="form-control form-control-alternative">
                                        <option >1</option>
                                        <option> undone</option>
                                    </select>
                                </div>

                                <div class="form-group">
                                    <label class="form-control-label" for="name">{{ __('Assigned Employee') }}</label>
                                    <input type="text" name="name"  class="form-control form-control-alternative" placeholder="{{ __('Operations name') }}" value="{{$task->name}}" >
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4" value="Update">{{ __('Update') }}</button>
                                </div>
                            </div>
                        </form>
                  

                    
                    
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/task/index.blade.php
@extends('layouts.app')

@section('content')
@include('layouts.headers.list')

  <div class="container-fluid mt--7">
        <div class="row float-right">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Tasks') }}</h3>
                            </div>
                            @cannot('employee')<div class="col-6 text-right">
                                <a href="{{ route('task.create') }}" class="btn btn-sm btn-primary">{{ __('Add New Task') }}</a>
                            </div> @endcannot

                        </div>
                    </div>
                    
                  
               
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Title') }}</th>
                                    <th scope="col">{{ __('Operations Name') }}</th>
                                    <th scope="col">{{ __('Due Date') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($tasks as $task)
                                    <tr>
                                        <td>{{ $task->title }}</td>
                                        <td>{{ $task->name }}</td>
                                        <td>{{ $task->due_date }}</td>
                                        <td>
                                        @if($task->status == 0)
                                        @can('admin')
                                    
                                        <a href = "{{route('doneTask' , $task->id)}}">Mark as Done</a>
                                        @endcan
                                        @else
                                        <small class="btn btn-success btn-sm" role="alert">Done!</small>
                                        @endif
                            
                                        </td>
                                       @cannot('employee')
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                   
                                                        <form action="{{ route('task.destroy', $task) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            
                                                            <a class="dropdown-item" href="{{ route('task.edit', $task) }}">{{ __('Edit') }}</a>
                                                            <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this task?") }}') ? this.parentElement.submit() : ''">
                                                                {{ __('Delete') }}
                                                            </button>
                                                        </form>    
                                                    
                                                       
                                                </div>
                                            </div>
                                        </td>
                                        @endcannot
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
<!-- end of code task table -->

<!-- topic table -->


<div class="container-fluid mt--7">
        <div class="row float-left">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Topics') }}</h3>
                            </div>
                            @cannot('employee')<div class="col-6 text-right">
                                <a href="{{ route('topic.create') }}" class="btn btn-sm btn-primary">{{ __('Add New Topic') }}</a>
                            </div> @endcannot

                          

                        </div>
                    </div>
                    
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Title') }}</th>
                                    <th scope="col">{{ __('Hour') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($topics as $topic)
                                    <tr>
                                        <td>{{ $topic->topic_title }}</td>
                                        <td>{{ $topic->topic_hour }}</td>
                                        <td>
                                        @if($topic->status == 0)
                                        @can('admin')
                                    
                                        <a href = "{{route('done' , $topic->id)}}">Mark as Done</a>
                                        @endcan
                                        @else
                                        <small class="btn btn-success btn-sm" role="alert">Done!</small>
                                        @endif
                                    
                                        </td>
                                       @cannot('employee')
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                   
                                                        <form action="{{ route('topic.destroy', $topic) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            
                                                            <a class="dropdown-item" href="{{ route('topic.edit', $topic) }}">{{ __('Edit') }}</a>
                                                            <button type="button" class="dropdown-item" onclick="confirm('{{ __("Are you sure you want to delete this topic?") }}') ? this.parentElement.submit() : ''">
                                                                {{ __('Delete') }}
                                                            </button>
                                                        </form>    
                                                    
                                                       
                                                </div>
                                            </div>
                                        </td>
                                        @endcannot
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    
                </div>
            </div>
        </div>
            
       
    </div>

<!-- end of code topice table -->


@endsection